version: '3.8'

services:
  gateway-service:
    build: ./backend/gateway
    ports:
      - "3000:3000"
    env_file:
      - ./backend/gateway/.env
    volumes:
      - ./backend/gateway:/app
      - /app/node_modules
    depends_on:
      - auth-service
      - user-service
      - route-service
      - incident-service
      - alert-service
      - stats-service
      - ai-service
    restart: unless-stopped

  auth-service:
    build: ./backend/auth-service
    ports:
      - "3001:3001"
    env_file:
      - ./backend/auth-service/.env
    volumes:
      - ./backend/auth-service:/app
      - /app/node_modules
    depends_on:
      - mongo

  user-service:
    build: ./backend/user-service
    ports:
      - "3002:3002"
    env_file:
      - ./backend/user-service/.env
    volumes:
      - ./backend/user-service:/app
      - /app/node_modules
    depends_on:
      - mongo

  route-service:
    build: ./backend/route-service
    ports:
      - "3003:3003"
    env_file:
      - ./backend/route-service/.env
    volumes:
      - ./backend/route-service:/app
      - /app/node_modules
    depends_on:
      - mongo
      - incident-service
      - alert-service
      - stats-service
      - ai-service

  incident-service:
    build: ./backend/incident-service
    ports:
      - "3004:3004"
    env_file:
      - ./backend/incident-service/.env
    volumes:
      - ./backend/incident-service:/app
      - /app/node_modules
    depends_on:
      - mongo

  alert-service:
    build: ./backend/alert-service
    ports:
      - "3005:3005"
    env_file:
      - ./backend/alert-service/.env
    volumes:
      - ./backend/alert-service:/app
      - /app/node_modules
    depends_on:
      - mongo

  stats-service:
    build: ./backend/stats-service
    ports:
      - "3006:3006"
    env_file:
      - ./backend/stats-service/.env
    volumes:
      - ./backend/stats-service:/app
      - /app/node_modules
    depends_on:
      - mongo

  ai-service:
    build: ./backend/ai-service
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
