import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

const styles = StyleSheet.create({
  circleButton: {
    alignItems: "center",
    backgroundColor: "#007bff", 
    borderRadius: 28,
    bottom: 180,
    elevation: 5,
    height: 56,
    justifyContent: "center",
    position: "absolute",
    right: 20,
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 4,
    width: 56,
  },
  container: {
    flex: 1,
  },
  iconSpacing: {
    marginRight: 8,
  },
  iconStartButton: {
    alignItems: "center",
    backgroundColor: "#007bff",
    borderRadius: 30,
    bottom: 90,
    elevation: 5,
    justifyContent: "center",
    padding: 14,
    position: "absolute",
    right: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
  },
  logoutButton: {
    backgroundColor: "#fff",
    borderRadius: 50,
    elevation: 5,
    padding: 10,
    position: "absolute",
    right: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    top: 60,
    zIndex: 20,
  },
  map: {
    height,
    width,
  },
  recenterButton: {
    backgroundColor: "white",
    borderRadius: 50,
    bottom: 100,
    elevation: 5,
    padding: 12,
    position: "absolute",
    right: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    zIndex: 10,
  },
  resultItem: {
    borderBottomColor: "#eee",
    borderBottomWidth: 1,
    padding: 12,
  },
  resultList: {
    backgroundColor: "white",
    borderRadius: 8,
    elevation: 5,
    left: 0,
    marginHorizontal: 10,
    maxHeight: 150,
    position: "absolute",
    right: 0,
    zIndex: 10,
  },
  searchContainer: {
    alignSelf: "flex-start",
    marginLeft: 25,
    position: "absolute",
    top: 65,
    width: "75%",
    zIndex: 15,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    paddingHorizontal: 6,
    paddingVertical: 6,
  },
  searchRow: {
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: 8,
    elevation: 2,
    flexDirection: "row",
    height: 45,
    marginBottom: 10,
    paddingHorizontal: 10, // ⬅️ hauteur standard
  },
  startButton: {
    alignSelf: "center",
    backgroundColor: "#007bff",
    borderRadius: 10,
    bottom: 100,
    elevation: 5,
    paddingHorizontal: 20,
    paddingVertical: 12,
    position: "absolute",
  },
  startButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
  summaryBox: {
    backgroundColor: "white",
    borderRadius: 8,
    bottom: 20,
    elevation: 5,
    left: 20,
    padding: 15,
    position: "absolute",
    right: 20,
  },

  summaryText: {
    fontSize: 16,
    marginBottom: 5,
  },
  validateButton: {
    position: "absolute",
    top: height / 2 - 30, // centré verticalement
    left: width / 2 - 100, // largeur divisée par 2 - moitié du bouton
    width: 200, // ✅ réduit
    backgroundColor: "#28a745",
    paddingVertical: 12,
    borderRadius: 20,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 30,
    elevation: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  validateButtonText: {
    color: "white",
    fontSize: 17,
    fontWeight: "bold",
    marginLeft: 8,
  },
});

export default styles;
