version: '3.8'
services:
  frontend:
    build: ./supmap-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  backend:
    image: node:16
    working_dir: /app
    volumes:
      - ./supmap-backend:/app
    command: npm start
    ports:
      - "5000:5000"
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: supmap
    ports:
      - "5432:5432"